name: project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tindercard: ^0.2.0
  newsapi: ^1.0.9
  equatable: ^1.2.5
  google_fonts: ^1.1.0
  sqflite: ^1.3.0
  path_provider: ^1.6.18
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  url_launcher: ^5.7.8
  flutter_dotenv: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Garamond
      fonts:
        - asset: fonts/EBGaramond-Regular.ttf
        - asset: fonts/EBGaramond-Italic.ttf
          style: italic
        - asset: fonts/EBGaramond-Bold.ttf
          weight: 700
        - asset: fonts/EBGaramond-BoldItalic.ttf
          weight: 700
          style: italic

